In [ ]:
import bisect
import sys

HAYSTACK = [1, 4, 5, 6, 8, 12, 15, 20, 21, 23, 23, 26, 29, 30]
NEEDLES = [0, 1, 2, 5, 8, 10, 22, 23, 29, 30, 31]

ROW_FMT = '{0:2d} @ {1:2d}  {2}{0:<2d}'

def demo(bisect_fn):
    for neddle in reversed(NEEDLES):
        position = bisect_fn(HAYSTACK, neddle)
        offset = position * '   |'
        print(ROW_FMT.format(neddle, position, offset))

if __name__ == '__main__':
    if sys.argv[-1] == 'left':
        bisect_fn = bisect.bisect_left
    else:
        bisect_fn = bisect.bisect
    
    print('DEMO: ', bisect_fn.__name__)
    print('haystack->', '  '.join('%2d' % n for n in HAYSTACK))
    demo(bisect_fn)
pass

In [ ]:
import bisect
import sys

HAYSTACK = [1, 4, 5, 6, 8, 12, 15, 20, 21, 23, 23, 26, 29, 30]
NEEDLES = [0, 1, 2, 5, 8, 10, 22, 23, 29, 30, 31]

ROW_FMT = '{0:2d} @ {1:2d}  {2}{0:<2d}'

def demo(bisect_fn):
    for neddle in reversed(NEEDLES):
        position = bisect_fn(HAYSTACK, neddle)
        offset = position * '   |'
        print(ROW_FMT.format(neddle, position, offset))

if __name__ == '__main__':
    if sys.argv[-1] == 'left':
        bisect_fn = bisect.bisect_left
    else:
        bisect_fn = bisect.bisect
    
    print('DEMO: ', bisect_fn.__name__)
    print('haystack->', '  '.join('%2d' % n for n in HAYSTACK))
    demo(bisect_fn)
pass

In [ ]:
def garde(score, breakpoints = [60, 70, 80, 90], grades = 'FDCBA'):
    i = bisect.bisect(breakpoints, score)
    return grades[i]

[garde(score) for score in [33, 99, 77, 70, 89, 90, 100]]

## 2.8.2 用 bisect.insort 插入新元素

In [ ]:
import bisect
import random

SIZE = 7

random.seed(1729)

my_list = []
for i in range(SIZE):
    new_item = random.randrange(SIZE*2)
    bisect.insort(my_list, new_item)
    print('%2d  ->' % new_item, my_list)

10  -> [10]
 0  -> [0, 10]
 6  -> [0, 6, 10]
 8  -> [0, 6, 8, 10]
 7  -> [0, 6, 7, 8, 10]
 2  -> [0, 2, 6, 7, 8, 10]
10  -> [0, 2, 6, 7, 8, 10, 10]


## 2.9.1 数组

在只包含数字时 array.array 比 list 更高效  
数组支持所有跟可变序列有关的操作： .pop .insert .extend  
同时提供从文件读取和存入文件更快的方法： .frombytes .tofile  

In [ ]:
# 创建一个有1000万个随机浮点数的数组，并存放再读取
from array import array
from random import random
floats = array('d', (random() for i in range(10**7)))
floats[-1]

fp = open('floats.bin', 'wb')
floats.tofile(fp)
fp.close()

floats2 = array('d')
fp = open('floats.bin', 'rb')
floats2.fromfile(fp, 10**7)
fp.close()
floats2[-1]

floats == floats2

True

利用一个可迭代对象来建立双精度浮点数组（类型码为 'd' ），这里我们用的可迭代对象是一个生成器表达式。

## 2.9.2 内存视图

memoryview 是一个内置类，可以让用户在不复制内容的情况下操作同一个数组的不同切片  
memoryview.cast 的概念与数组模块类似，能用不同的方式读写同一块内存，它会将同一块内存的内容打包成一个全新的 memoryview 对象给用户

In [ ]:
import array
numbers = array.array('h', [-2, -1, 0, 1, 2])
memv = memoryview(numbers)
len(memv)

5

创建含有5个短整型有符号整数的数组（状态码 'h'），并生成 memoryview

In [ ]:
memv[0]

-2

memv中的 5 个元素和数组里没有区别

In [ ]:
memv_oct = memv.cast('b')
memv_oct.tolist()

[-2, -1, -1, -1, 0, 0, 1, 0, 2, 0]

将 memv 的内容转换成 'B' 类型，即无符号数组并给 memv_oct

In [ ]:
memv_oct[5] = 4
numbers

array('h', [-2, -1, 1024, 1, 2])

因为将占2个字节的整数的高位字节改成了 4， 所以这个有符号整数的值变成了 1024

## 2.9.3 NumPy和SciPy

In [ ]:
# NumPy 二维数组的基本操作
import numpy
a = numpy.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
type(a)

numpy.ndarray

新建一个 0~11 的整数的 numpy.ndarray 然后将它打印出来

In [ ]:
# 查看数组维度，它是一个一维的，有 12 个 元素的数组
a.shape

(12,)

In [ ]:
# 将数组变成二维的并打印
a.shape = 3, 4
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# 打印第二行
a[2]

array([ 8,  9, 10, 11])

In [ ]:
# 打印第二行第一列
a[2:1]

array([], shape=(0, 4), dtype=int32)

In [ ]:
# 打印第一列
a[:, 1]

array([1, 5, 9])

In [ ]:
# 交换行和列
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

## 2.9.4 双向队列

In [ ]:
# 使用双向队列
# maxlen 是可选参数，代表队列可容纳的元素数量，一旦设定便不可修改
from collections import deque
dq = deque(range(10), maxlen=10)
dq

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
dq.rotate(3)
dq

deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6])

In [ ]:
# 队列的旋转接受参数 n， 当 n > 0 时， 队列的最右边的 n 个元素会被移动到队列的左边。 当 n < 0 时，最左边的 n 个元素会被移动到右边
dq.rotate(-4)
dq

deque([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [ ]:
# 当试图对一个已满的队列做头部添加时，它尾部的元素会被删除掉
dq.appendleft(-1)
dq

deque([-1, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 在尾部添加 3 个元素会挤掉 -1、 1 和 2
dq.extend([11, 22, 33])
dq

deque([3, 4, 5, 6, 7, 8, 9, 11, 22, 33])

In [ ]:
# extendleft(iter) 方法会把迭代器里的元素逐个添加到双向队列的左边，因此迭代器里的元素会逆序出现在队列里
dq.extendleft([10, 20, 30, 40])
dq

deque([40, 30, 20, 10, 3, 4, 5, 6, 7, 8])

append 和 popleft 都是原子操作，也就是说 deque 可以在多线程程序中安全地当作先进先出队列使用，而使用者不需要担心资源锁的问题