In [16]:
# NumPy 二维数组的基本操作
import numpy
a = numpy.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
type(a)

numpy.ndarray

新建一个 0~11 的整数的 numpy.ndarray 然后将它打印出来

In [18]:
# 查看数组维度，它是一个一维的，有 12 个 元素的数组
a.shape

(12,)

In [19]:
# 将数组变成二维的并打印
a.shape = 3, 4
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
# 打印第二行
a[2]

array([ 8,  9, 10, 11])

In [21]:
# 打印第二行第一列
a[2:1]

array([], shape=(0, 4), dtype=int32)

In [22]:
# 打印第一列
a[:, 1]

array([1, 5, 9])

In [23]:
# 交换行和列
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])